---
- name: Save Router Configs (IOS)
  hosts: R2
  gather_facts: true
  connection: local

  tasks:

  - name: Supply Credentials
    include_vars: secrets.yml

  - name: Use Credentials
    set_fact:
     provider:
      host: "{{ ansible_host }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"

  - name: Show Run
    ios_command:
     provider: "{{ provider }}"
     commands:
      - show run
    register: show_run

  - name: Print Output
    debug: msg=show_run.stdout

  - name: Copy and create file
    copy: 
     content: "{{ show_run.stdout }}"
     dest: "/root/ANSIBLE/CFGS/{{ inventory_hostname }}.txt"






